# Generated by Django 5.1.1 on 2024-10-08 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Data_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
