# Generated by Django 5.1.1 on 2024-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0003_alter_noticia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
