# Generated by Django 5.1.2 on 2024-11-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0005_curso_remove_noticia_data_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='edicao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cead.curso'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
