# Generated by Django 5.1.1 on 2024-11-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0006_alter_noticia_descricao_alter_noticia_edicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cead.coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cead.curso')),
            ],
        ),
    ]
