# Generated by Django 5.1.1 on 2024-11-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0007_coordenador_polo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='id_curso',
            new_name='curso',
        ),
    ]
