# Generated by Django 5.1.1 on 2024-11-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0008_rename_id_curso_noticia_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='curso',
        ),
    ]
