# Generated by Django 5.1.2 on 2024-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0010_coordenador_edicao_coordenador_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('formacao', models.TextField(max_length=255)),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='polo',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
