# Generated by Django 5.1.1 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0011_mediador_alter_contato_nome_alter_coordenador_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=11),
        ),
        migrations.AlterField(
            model_name='mediador',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediador',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=11),
        ),
    ]
