# Generated by Django 5.1.1 on 2024-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0012_alter_coordenador_email_alter_coordenador_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10),
        ),
    ]
