# Generated by Django 5.1.1 on 2024-11-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0014_alter_coordenador_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='publicacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
