# Generated by Django 5.1.1 on 2024-11-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0015_alter_coordenador_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediador',
            name='curso',
            field=models.ForeignKey(default='teste', on_delete=django.db.models.deletion.CASCADE, to='cead.curso'),
        ),
        migrations.AddField(
            model_name='polo',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cead.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polo',
            name='mediador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cead.mediador'),
            preserve_default=False,
        ),
    ]
