# Generated by Django 5.1.1 on 2024-11-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0016_mediador_curso_polo_curso_polo_mediador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediador',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cead.curso'),
        ),
    ]
