# Generated by Django 5.1.1 on 2024-11-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0019_remove_mediador_curso_remove_polo_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cead.coordenador'),
            preserve_default=False,
        ),
    ]
