# Generated by Django 5.1.1 on 2024-11-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0022_alter_curso_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediador',
            name='curso_polo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mediadores', to='cead.cursopolo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursopolo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_polos', to='cead.curso'),
        ),
        migrations.AlterField(
            model_name='cursopolo',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_polos', to='cead.polo'),
        ),
    ]
