# Generated by Django 5.1.1 on 2024-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0023_mediador_curso_polo_alter_cursopolo_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursopolo',
            name='edicao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cursopolo',
            name='publicacao',
            field=models.DateField(auto_now_add=True, default=101010),
            preserve_default=False,
        ),
    ]
