# Generated by Django 5.1.1 on 2024-11-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0014_mediador_situacao'),
        ('cead', '0024_cursopolo_edicao_cursopolo_publicacao'),
    ]

    operations = [
    ]
