# Generated by Django 5.1.2 on 2024-11-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0025_merge_20241119_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=100)),
                ('telefone', models.IntegerField(default='7499999999')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='cead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cead.cead'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NoticiaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_curso', to='cead.curso')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_curso', to='cead.noticia')),
            ],
        ),
    ]
