# Generated by Django 5.1.1 on 2024-11-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0025_merge_20241119_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorPolos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_polos', to='cead.coordenador')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_polos', to='cead.polo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gestor', 'polo'), name='unique_gestor_polo')],
            },
        ),
    ]
