# Generated by Django 5.1.2 on 2024-11-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0026_cead_noticia_cead_noticiacurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='cead',
        ),
    ]
