# Generated by Django 5.1.1 on 2024-11-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0026_gestorpolos'),
        ('cead', '0027_remove_noticia_cead'),
    ]

    operations = [
    ]
