# Generated by Django 5.1.1 on 2024-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0030_coordenadorcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenadorcurso',
            name='entrada',
            field=models.DateField(auto_now_add=True, default=0.0004491555874955084),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenadorcurso',
            name='saida',
            field=models.DateField(default=0.0004491555874955084),
            preserve_default=False,
        ),
    ]
