# Generated by Django 5.1.1 on 2024-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0031_coordenadorcurso_entrada_coordenadorcurso_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadorcurso',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
