# Generated by Django 5.1.1 on 2024-11-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0033_remove_noticia_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediador',
            name='curso_polo',
        ),
        migrations.RemoveField(
            model_name='mediador',
            name='situacao',
        ),
        migrations.CreateModel(
            name='Mediacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField(auto_now_add=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('curso_polos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='cead.cursopolo')),
                ('mediador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='cead.mediador')),
            ],
        ),
    ]
