# Generated by Django 5.1.1 on 2024-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0034_remove_mediador_curso_polo_remove_mediador_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacao',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='', max_length=10),
        ),
    ]
