# Generated by Django 5.1.1 on 2024-11-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0035_mediacao_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediadorCursoPolos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='VIRTUAL', max_length=10)),
                ('entrada', models.DateField(auto_now_add=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('curso_polos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MediadorCurso_Polos', to='cead.cursopolo')),
                ('mediador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MediadorCurso_Polos', to='cead.mediador')),
            ],
        ),
        migrations.DeleteModel(
            name='Mediacao',
        ),
    ]
