# Generated by Django 5.1.1 on 2024-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0038_mediacao_delete_mediadorcursopolos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacao',
            name='modalidade',
            field=models.CharField(choices=[('Presencial', 'PRESENCIAL'), ('Virtual', 'VIRTUAL')], default='VIRTUAL', max_length=10),
        ),
    ]
