# Generated by Django 5.1.1 on 2024-11-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0039_alter_mediacao_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacao',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='VIRTUAL', max_length=10),
        ),
    ]
