# Generated by Django 5.1.1 on 2024-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0034_remove_gestorpolos_unique_gestor_polo_and_more'),
        ('cead', '0040_alter_mediacao_modalidade'),
    ]

    operations = [
    ]
