# Generated by Django 5.1.1 on 2024-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0041_merge_20241128_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polo',
            name='gestor',
        ),
    ]
