# Generated by Django 5.1.1 on 2024-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0042_remove_polo_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='situacao',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
    ]
