# Generated by Django 5.1.2 on 2024-12-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0043_alter_gestor_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='coordenador',
        ),
    ]
