# Generated by Django 5.1.2 on 2024-12-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0044_remove_curso_coordenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='situacao',
        ),
    ]
