# Generated by Django 5.1.1 on 2024-12-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0045_remove_coordenador_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadorcurso',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_curso', to='cead.curso'),
        ),
    ]
