# Generated by Django 5.1.1 on 2024-12-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0046_alter_coordenadorcurso_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacao',
            name='curso_polos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='cead.cursopolo'),
        ),
        migrations.AlterField(
            model_name='mediacao',
            name='mediador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='cead.mediador'),
        ),
    ]
