# Generated by Django 5.1.1 on 2024-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0047_alter_mediacao_curso_polos_alter_mediacao_mediador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='situacao',
        ),
    ]
