# Generated by Django 5.1.1 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0048_alter_noticia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
