# Generated by Django 5.1.1 on 2024-12-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0048_remove_gestor_situacao'),
        ('cead', '0050_alter_noticia_arquivo'),
    ]

    operations = [
    ]
