# Generated by Django 5.1.1 on 2024-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0051_merge_20241205_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
