# Generated by Django 5.1.1 on 2024-12-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0051_merge_20241205_1056'),
        ('cead', '0052_alter_noticia_arquivo'),
    ]

    operations = [
    ]
