# Generated by Django 5.1.2 on 2024-12-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0054_coordenador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cead',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='cead',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cead',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mediacao',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediador',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediador',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
