# Generated by Django 5.1.2 on 2024-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0055_remove_cead_situacao_alter_cead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cead',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='mediador',
            name='telefone',
            field=models.CharField(default='7499999999', max_length=15),
        ),
    ]
