# Generated by Django 5.1.1 on 2025-02-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0056_alter_cead_telefone_alter_contato_telefone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
