# Generated by Django 5.1.1 on 2024-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_noticia_data_mod_alter_noticia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
