# Generated by Django 5.1.1 on 2024-12-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=100)),
                ('telefone', models.IntegerField(default='7499999999')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=100)),
                ('telefone', models.IntegerField(default='7499999999')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobre', models.TextField()),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=100)),
                ('telefone', models.IntegerField(default='7499999999')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('formacao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mediador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=100)),
                ('telefone', models.CharField(default='7499999999', max_length=11)),
                ('formacao', models.TextField(max_length=255)),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=900)),
                ('arquivo', models.FileField(blank=True, upload_to='uploads/')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField(auto_now_add=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_curso', to='coo.coordenador')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_curso', to='coo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('matricula', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='CursoPolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_polos', to='coo.curso')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_polos', to='coo.polo')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ementa', models.TextField()),
                ('modulo', models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º')], max_length=10)),
                ('ch', models.IntegerField()),
                ('arquivo', models.FileField(upload_to='')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(upload_to='')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Mediacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='VIRTUAL', max_length=10)),
                ('entrada', models.DateField(auto_now_add=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('curso_polos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='coo.cursopolo')),
                ('mediador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacao', to='coo.mediador')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_curso', to='coo.curso')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_curso', to='coo.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('arquivo', models.FileField(upload_to='')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('edicao', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coo.curso')),
            ],
        ),
        migrations.CreateModel(
            name='GestorPolos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateField(auto_now_add=True)),
                ('saida', models.DateField(blank=True, null=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_polos', to='coo.gestor')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_polos', to='coo.polo')),
            ],
        ),
    ]
