# Generated by Django 5.1.1 on 2025-02-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cead', '0057_delete_contato'),
        ('coo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cead.curso'),
        ),
    ]
