# Generated by Django 5.1.1 on 2025-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coo', '0002_alter_contato_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
